const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../core.js');
const bank=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../questions.json')));let tests=0;
function test(name,fn){fn();tests++;console.log('PASS',name);}
test('All six manuals and three levels selected strictly',()=>{for(const s of ['ADOC','DRCV','GO'])for(const y of ['1re','2e'])for(const level of ['medium','hard','expert']){const pool=bank.filter(q=>q.subject===s&&q.year===y);const qs=C.pick(pool,20,level);assert(qs.length>0);assert(qs.every(q=>q.difficulty===level));assert.equal(new Set(qs.map(q=>q.id)).size,qs.length);}});
test('Reasoning families excluded from same selection',()=>{const selected=C.pick(bank,238,'mixed');const families=selected.filter(q=>q.family).map(q=>q.family);assert.equal(families.length,new Set(families).size);});
test('Mixed level balance when pool allows it',()=>{const pool=bank.filter(q=>q.subject==='DRCV'&&q.year==='1re');const qs=C.pick(pool,9,'mixed',[],[],()=>.5);for(const l of ['medium','hard','expert'])assert(qs.filter(q=>q.difficulty===l).length>=2);});
test('Recent questions and previous round penalized',()=>{const pool=Array.from({length:20},(_,i)=>({id:String(i),subject:'X',year:'1',chapter:'1',notion:String(i),style:'method',difficulty:'hard',question:'Question '+i}));const a=C.pick(pool,5,'hard',[],[],()=>.5),b=C.pick(pool,5,'hard',a.map(q=>q.id),a.map(q=>q.id),()=>.5);assert(b.every(q=>!a.some(p=>p.id===q.id)));});
test('Empty pool and insufficient level do not fall back',()=>{assert.deepEqual(C.pick([],5,'expert'),[]);assert.deepEqual(C.pick(bank.filter(q=>q.difficulty==='hard'),5,'expert'),[]);});
test('Deadline and round identity',()=>{const r={id:'x',round:1,current_index:0,duration:20,question_started_at:new Date(1000).toISOString()};assert.equal(C.remaining(r,21000),0);assert.equal(C.remaining(r,999999),0);assert.notEqual(C.questionKey(r),C.questionKey({...r,round:2}));});
test('Choice validation preserves numeric signs',()=>{const q={...bank[0],choices:['+44','−44','+80','+62']};assert(C.validateBank([q]));assert.throws(()=>C.validateBank([{...q,choices:['44','44','80','62']}]));});
(async()=>{
 const ctx={window:{},document:{visibilityState:'visible'},navigator:{onLine:true},crypto:{randomUUID:()=>String(Math.random())},AbortController,Date,console,setTimeout,clearTimeout,Math};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../sync.js'),'utf8'),ctx);
 let resolves=[],calls=0,accepted=[],removed=0,subscriptions=[];const client={rpc(){calls++;return{abortSignal(){return new Promise(r=>resolves.push(r));}}},channel(){const ch={on(e,f,cb){this.cb=cb;return this},subscribe(cb){this.status=cb;subscriptions.push(this);return this}};return ch},async removeChannel(){removed++}};
 const sync=new ctx.window.ArenaSync(client,s=>accepted.push(s.sync_revision),()=>{});const snapshot=(id,n)=>({data:{room:{id,revision:n},sync_revision:n,server_now:new Date().toISOString()}});
 let first=sync.attach('a','token');assert.equal(calls,1);await sync.pull();assert.equal(calls,1);resolves.shift()(snapshot('a',5));await first;clearTimeout(sync.timer);assert.deepEqual(accepted,[5]);tests++;console.log('PASS One in-flight snapshot');
 let stale=sync.pull();resolves.shift()(snapshot('a',4));await stale;assert.deepEqual(accepted,[5]);clearTimeout(sync.timer);tests++;console.log('PASS Out-of-order snapshot rejected');
 let old=sync.pull(),fresh=sync.attach('b','token');resolves.shift()(snapshot('a',99));await old;resolves.shift()(snapshot('b',1));await fresh;assert.deepEqual(accepted,[5,1]);assert(removed>=1);clearTimeout(sync.timer);tests++;console.log('PASS Old room response ignored, subscription removed');
 let hiddenCalls=calls;ctx.document.visibilityState='hidden';await sync.pull();assert.equal(calls,hiddenCalls);clearTimeout(sync.timer);ctx.document.visibilityState='visible';ctx.navigator.onLine=false;await sync.pull();assert.equal(calls,hiddenCalls);clearTimeout(sync.timer);tests++;console.log('PASS Hidden and offline do not poll');
 ctx.navigator.onLine=true;let fatal;sync.onFatal=e=>fatal=e.message;let bad=sync.pull();resolves.shift()({error:{message:'Salle expirée ou introuvable'}});await bad;assert.equal(sync.room,null);assert(fatal);tests++;console.log('PASS Invalid room stops cleanly');sync.stop();
 console.log('TOTAL',tests);
})().catch(e=>{console.error(e);process.exitCode=1});
